module.exports = {
  id: 'js',
  title: 'JavaScript',
  nested: [
    require('./arith'),
    require('./bitwise-operators'),
    require('./falsy'),
    require('./logical-operators'),
    require('./template-strings'),
    require('./loops'),
    require('./map-reduce'),
    require('./reduce-filter'),
    require('./set-ops'),
    require('./regex-meta-chars'),
    require('./desc-to-regex'),
    require('./regex-match'),
    require('./event-loop'),
    require('./promises-true-false'),
    require('./promise-results'),
    // require('./prototype-true-false'),
    // require('./var-let-rules'),
    // require('./var-let-code'),
    // require('./add-concat'),
    // require('./conversions'), 
  ],
};

